### ISSUE TITLE
QuickDail is slowing down...

### ISSUE THREAD

**Issue by xgamerg1rl** [MatMoul/quickdial-webext#104]
Hi there,
i've been using QuickDail since the last like 6 month and it worked all fine (Props to you and much thanks :) )
but in the last 2 Days (maybe there was an Update) it slows down when I open it in a new Tab...
Like after 1-2 Secounds it works just as always... :/

greetings from Germany,
Michelle

**Comment by jy-fr** [comment]
Hello,
Same here. Very very very slow since few days.
I don't know why. Nothing changed.
xUbuntu 18.04

**Comment by MatMoul** [comment]
No change on the extention...
On my config, I don't encouter this problem...
ArchLinux + KDE + FF61.0.2

Can you test without other extention?

**Comment by jy-fr** [comment]
It's arranged. 
On a new profile, with only quick dial and my old bookmarks, everything works fine.
On my usual profile, I watched what extensions had been updated recently to see if there was any incompatibility ... and the problem is with "Flash Video Downloader 16.1.1 by FVD media". 
Disabling it and all works again.
thanks.

**Comment by xgamerg1rl** [comment]
Yea. Saw it too :) man... I hate those kind of updates -_-
