### ISSUE TITLE
Blank 

### ISSUE THREAD

**Issue by mrmrva** [MatMoul/quickdial-webext#130]
My QD has became blank today.
Tried disabling all other add-ons but same issue. Set QD as home page again issue remains.
Firefox 66.07b
EDIT: There is no menu when I right click on QD page to add new bookmarks.
Where are bookmarks saved so I can try to back them up?
![capture](https://user-images.githubusercontent.com/47577690/52669736-2e5b4f00-2f17-11e9-98d4-29049b3143ce.PNG)

**Comment by mrmrva** [comment]
Resolved by installing Firefox over current version

**Comment by MatMoul** [comment]
@mrmrva Thanks for return

**Comment by MaximilianKohler** [comment]
Reinstalling Firefox isn't a solution for me since I'm running the portableapps.com version. 

I think it may have been caused by Firefox's sync. Possible trigger:

I have one instance open on my PC, then I have another version on a USB that I used on my laptop. Firefox sync detects both versions as the same device/instance, and I think that's what caused the issue. 

I tried signing out of FF sync without deleting data and that didn't fix it. 

I tried creating a new installation/instance of FF and signing into sync, but it didn't fully restore my browser. Quick dial was working but my customizations were gone. 

I closed FF and took the old "profile" folder and put it in the new/clean version. Reopened FF and Quick dial was broken again. FF sync was still disabled on the old version. 

Switched the "profile" folder again for the new/clean version and it works (missing customizations). 

I copied over the browser-extension-data folder from the old V to new V, that did nothing. I replaced the new "extensions" folder with the old one. Still no restoration of my old settings. 

I deleted all files in the new profile folder, keeping all folders, and pasted in the files from the old version. Quick dial is still working, my customizations are not restored, but one - the grid layout - is changed. 

From the full old profile I deleted 4 folders: shader-cache, shortcutcache, startupcache, and storage. That causes quick dial to work, but my customizations are gone. I restored each of the 4 folders one at a time, and found "storage" to be the culprit of the blank quick dial page. 

To confirm, I restored and tested the full original firefox version/folder (blank page), closed it, deleted the "storage" folder, and confirmed that quick dial works again but my customizations are lost. 

I confirmed that it's the /storage/default folder that's the issue. 

I confirmed it's one of the moz-extension+++ folders. 

I tried moving columns of moz-extension+++ folders at a time to narrow it down, but that did not work and it seems that 8 of them get automatically re-created, and that results in the blank page. All 8 files that get recreated contain a single ".metadata-v2" file, 193 bytes. 

Any suggestions?
