### ISSUE TITLE
main bar icon action

### ISSUE THREAD

**Issue by Stephdv** [MatMoul/quickdial-webext#15]
Hi,
Just one more resquest : could you add the feature to **not** add a tab when you click on the main bar menu icon ?
Very good work thank you.

**Comment by MatMoul** [comment]
It's certainly possible, I retag to "Possible future enhancememt"

**Comment by scienmind** [comment]
Somewhat close to topic, though not really:

Is there a proper way to set Quick Dial as "Home page"?
(so that, for example, opening new window via CTRL+N will open Quick Dial)

Setting home to simply `moz-extension://IDIDID-IDID...IDID-IDIDID/dial` is not practical, since extension's IDIDID varies between devices, so synced Home page won't work on any device but the original one.

**Comment by MatMoul** [comment]
Now, you have an option for this in Quick Dial settings in V 0.1.13
