### ISSUE TITLE
Quick Dial menu does not work on FF 84/85

### ISSUE THREAD

**Issue by kasatikoff** [MatMoul/quickdial-webext#162]
Quick Dial menu does not work on FF 84/85

Menu block is empty and not hidden

![FF-85_QD](https://user-images.githubusercontent.com/7024220/104004234-13aeb500-51d6-11eb-85c8-881cca15a280.png)

**Comment by Shne** [comment]
The reason for the breakage is that they have removed `menuItem` in Firefox 85: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/85#Removals_2
The reason is that it is deprecated and will be removed: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem
But for now it is hidden behind a flag: https://bugzilla.mozilla.org/show_bug.cgi?id=1680596 https://groups.google.com/g/mozilla.dev.platform/c/tc11BCenm2c?pli=1

So you can as a temporary measure re-enable it by setting the `dom.menuitem.enabled` flag to true in about:config.

In the longer run, this plugin should be updated, or its users will have to find an alternative.

**Comment by kasatikoff** [comment]
Thank you, that solved the problem

**Comment by MatMoul** [comment]
looking to fix it...
Give me some days...

**Comment by MatMoul** [comment]
Hello,
You can try to force update your addons and reset `dom.menuitem.enabled` flag.
I've rewrited the context menu with the limitations of the current API.
Now all is grouped in the child menu "Quick Dial"

**Comment by tidjidi** [comment]
Nice shot! Good job!
