### ISSUE TITLE
Import bookmarks & properties from FastDial

### ISSUE THREAD

**Issue by UltimateUser** [MatMoul/quickdial-webext#56]
As this add-on takes a whole lot of features from the well known Fast-Dial extension it would be nice if it could have an option to import previously stored bookmarks and properties (eg. image, title etc).

**Comment by MatMoul** [comment]
Sorry, I don't have time to do this.
Need contributors

**Comment by fernandosantucci** [comment]
This is very simple to do!
In the Firefox bookmarks manager, just rename the "Fast Dial" folder to "Quick Dial".

**Comment by alex-pancho** [comment]
I m developer, i use FastDial (FD) and QuickDial (QD)
Into FD all bookmarks saved into one bookmark folder. 
It was be great if you do import FD to QD
What type help you need? Whrite and may be i provide some help

**Comment by alex-pancho** [comment]
May be see FD for Chrome be helpfool for you, as i  read, new FF and Chrome addon very seems
https://chrome.google.com/webstore/detail/fast-dial/fdnbdgmkhikelgaohpgdpcecklddmpaj?hl=uk

**Comment by MatMoul** [comment]
@alex-pancho I don't have time to work on import script...
If you are a developer, you can try to make a PR with an import solution for FD or an other speed dial.
With FD, copying the bookmarks folder don't import custom background, dial icon and other settings...
It's an hard work because you need to learn all other speed dial file format...
