### ISSUE TITLE
All settings have been reset after the PC hardreset.

### ISSUE THREAD

**Issue by ZHenyayneHZ** [MatMoul/quickdial-webext#59]
Hello! I'm having an addon problem. While I was working on the Internet, my PC hung, which caused me to restart it. As a result, all add-on settings were reset to default. Can I restore them?

Data folder:
https://i.gyazo.com/9d48a472b84aa3ce835067b56a59d73c.png

**Comment by ZHenyayneHZ** [comment]
> Never encouter that... 

> 

If you are talking about 'my PC hung', then this is the wrong translation of Google translator, it will be more correct 'my PC is down' or 'my PC is frozen' :)
> I see a .corrupt file in your folder. Do you have tryed to copy it to storage.js? 

> 

Yes, this did not fix, the addon still creates the default storage.js, and my storage-file again marks as .corrupt.

**Comment by MatMoul** [comment]
I understood well for your PC have freezed...
For the storage.js, it's a JSON file...
It have chance that the corrupt file has truncked the end of the file.
If you can edit the file and close the JSON object, it's possible that your retrieve a part of your config.
But it's best to have backup...

**Comment by ZHenyayneHZ** [comment]
>  If you can edit the file and close the JSON object, it's possible that your retrieve a part of your config. 
>
The file is completely corrupted, there is no chance to restore it.

>  But it's best to have backup...
> 
Maybe you should add auto-backup to the addon?

**Comment by MatMoul** [comment]
webext are very restrictive...the freeze need to be handled from Firefox.try to open an issue on Firefox project.

**Comment by karolgrudzinski** [comment]
I installed Quick Dial today to test if it can replace Fast Dial but sadly I have to uninstall addon quickly. QD is quite nice but it has two major flaws:
1. It loads all pages without thumbnail at the same time. It crashes Firefox every time. Fast Dial loaded only a few pages at once.
2. Because of point 1. I have to run Firefox again and discovered that QD lost its settings!!!
I repeated points 1 and 2 and almost every time QD lost its settings.
So I downgraded Firefox to 56.0, disabled automatic updates, and restored my profile from backup.

**Comment by MatMoul** [comment]
@karolgrudzinski It's very strange that loading all pages crash your FF, I use a very old computer and I don't have problem.
It would be useful to provide me the grid size that you use.
In the future, I'll add a settings to load x tiles at a time.

**Comment by karolgrudzinski** [comment]
I used 4 rows and 8 columns.
